winget install M2Team.NanaZip
winget install Apple.iTunes
winget install Blizzard.BattleNet
winget install Discord.Discord
winget install Microsoft.Teams
winget install Microsoft.VisualStudioCode.User-x64
winget install Microsoft.WindowsTerminal
winget install PrivateInternetAccess.PrivateInternetAccess
winget install Valve.Steam
