export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

export VISUAL="nvim"
export EDITOR="nvim"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ADOTDIR="$XDG_DATA_HOME/zsh/antigen"
export HISTFILE="$XDG_DATA_HOME/zsh/history"
export LESSHISTFILE="$XDG_CACHE_HOME/less/history"
export GOPATH=~/.go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

hash gimp 2>/dev/null && export GIMP2_DIRECTORY="$XDG_CONFIG_HOME/gimp"

