source .antigen.zsh

antigen use oh-my-zsh
antigen bundle git
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
antigen bundle vi-mode
antigen bundle tarruda/zsh-autosuggestions
antigen bundle horosgrisa/autoenv
antigen bundle Tarrasch/zsh-bd
antigen bundle felixr/docker-zsh-completion
antigen bundle zsh-users/zsh-completions
antigen bundle srijanshetty/zsh-pandoc-completion
antigen bundle srijanshetty/zsh-pip-completion

antigen theme minimal

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

antigen apply

if [ -d "/opt/ros/indigo" ]; then
    source /opt/ros/indigo/setup.zsh
fi

if [ -d "$PATH:$HOME/.rvm/bin" ]; then
    export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
fi


eval `keychain --eval --quiet --agents ssh id_ed25519`
